version: "2"

services:
  web:
    ports:
      - "8000:8000"
    build: ./
    command: npm start
    volumes:
      - .:/app
    networks:
      - api

  mongo:
      ports:
        - "27017:27017"
      image: mongo:latest
      networks:
        - api

networks:
  api: