version: "2"

services:
  web:
    ports:
      - "3000:3000"
    build: ./
    command: npm start-react
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - api

  mongo:
      ports:
        - "27017:27017"
      image: mongo:latest
      networks:
        - api

networks:
  api:
