#!/bin/bash
if [ $? -eq 0 ]; then
    if [ "$1" == "node" ]; then
      docker-compose run --service-ports --rm web npm start-node
    else
      docker-compose run --service-ports --rm web npm start-react
    fi
fi
